### Variáveis (Use o Token e o ID do Restaurante que você criou)
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiNGVhYmI1LTEwOTgtNGUyYi1hZDk4LTc3YTA4Mzc2ZmQxMiIsInJvbGUiOiJDVVNUT01FUiIsImlhdCI6MTc2NzQ3MDQ1MSwiZXhwIjoxNzY3NTU2ODUxfQ.mWg2IkBtBpcXe6-VAJyhD3uXnJ5ZvhXK3FF-FIZhe3U
@restaurantId = c6048537-e504-4a7c-a138-af22cd1892d8

### Criar Categoria: Pizzas
POST http://localhost:3000/categories
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Pizzas Artesanais",
  "restaurantId": "{{restaurantId}}"
}

### ---------------------------------------------------------

### Listar Categorias do Restaurante
GET http://localhost:3000/categories/restaurant/{{restaurantId}}